### ISSUE TITLE
Health Bar disappearing

### ISSUE THREAD

**Issue by Juanpi21** [ImogenBits/tidyplates#1]
The Health Bar on the players' nameplate disappears when it fades out and back in, I'm not 100% sure it's this Addon causing it, but the only way I managed to bring the Health Bar back was disabling it. 
![image](https://user-images.githubusercontent.com/72284329/96354290-55e3c100-10d5-11eb-8686-6866756ec7d4.png)

**Comment by admiralshine** [comment]
I confirm. Only disabling the addon returns the health bar. Аnd my cat sad about it
![WoWScrnShot_101820_040838](https://user-images.githubusercontent.com/71872173/96355118-9f450800-10f7-11eb-9247-417dbd546de6.jpg)

**Comment by ImogenBits** [comment]
Thanks for the bug reports! I fixed the issue, the fix will be live with the next release version.
