### ISSUE TITLE
10.2.7.54577

### ISSUE THREAD

**Issue by Jeals** [ImogenBits/tidyplates#104]
Having issue with the new patch. It is not showing any frames at all now. I just checking to see if it just me or more people having the issue.

**Comment by Fayreon** [comment]
Same issue. I can get the default nameplates to show up by toggling 'Use Large Nameplates' in blizz settings, but that's temporary and drops with combat.

**Comment by jayznpeeps** [comment]
LUA error from bug grabber:

436x TidyPlates/TidyPlatesCore.lua:1126: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "@TidyPlates/TidyPlatesCore.lua"]:1126: in function <TidyPlates/TidyPlatesCore.lua:1126>
[string "@TidyPlates/TidyPlatesCore.lua"]:1152: in function <TidyPlates/TidyPlatesCore.lua:1149>
[string "@TidyPlates/TidyPlatesCore.lua"]:1235: in function <TidyPlates/TidyPlatesCore.lua:1200>
[string "@TidyPlates/TidyPlatesCore.lua"]:285: in function <TidyPlates/TidyPlatesCore.lua:273>
[string "@TidyPlates/TidyPlatesCore.lua"]:305: in function <TidyPlates/TidyPlatesCore.lua:293>
[string "@TidyPlates/TidyPlatesCore.lua"]:422: in function <TidyPlates/TidyPlatesCore.lua:412>
[string "@TidyPlates/TidyPlatesCore.lua"]:142: in function <TidyPlates/TidyPlatesCore.lua:121>

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "CENTER"

**Comment by Ric0chet-GitHub** [comment]
Same.  It's throwing thousands of errors:
271145x TidyPlates/TidyPlatesCore.lua:1126: bad argument # 1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))

**Comment by Ric0chet-GitHub** [comment]
For a temporary fix, edit  TidyPlates/TidyPlatesCore.lua   line 1126 as follows:

local function SetObjectJustify(object, horz, vert) object:SetJustifyH(horz); object:SetJustifyV(**"BOTTOM"**) end

I had disable & re-enable the addon, with accompanying reloads, to get this to take.

**Comment by Flowy94** [comment]
same here the addon making the game laggy and the plates are not showing only combo points.

**Comment by ImogenBits** [comment]
it's been fixed in the new release

**Comment by Flowy94** [comment]
thank you.
