### ISSUE TITLE
Update needed for 11.0

### ISSUE THREAD

**Issue by korgen63** [ImogenBits/tidyplates#107]
Not working with 11.0

**Comment by Flowy94** [comment]
Ye requires uppdate please

**Comment by passionINK** [comment]
yep doesnt work at all .
the plates are complete gone, only names show up. no access to the options of the addon.
Update required asap pls :3

**Comment by HiddeN00MasteR** [comment]
is this legit?

**Comment by Shelia2024** [comment]
I hope a quick fix is incoming, I can't play, I'm litterally blind with only seeing white name letters and no bars at all.

**Comment by httpsx** [comment]
> I hope a quick fix is incoming, I can't play, I'm litterally blind with only seeing white name letters and no bars at all.

use my fork as temporary solution, this will completely work if you had tideplates previously configured
https://github.com/httpsx/tidyplates

**Comment by DezLo19** [comment]
Thanks Httpsx for the workaround!

**Comment by Rusalopolis** [comment]
How do you use the work around?

**Comment by natehughes02** [comment]
> How do you use the work around?

Download this file: https://github.com/httpsx/tidyplates/blob/main/TidyPlates/TidyPlatesPanel.lua

Then go to C:\Program Files (x86)\World of Warcraft\_retail_\Interface\Addons\TidyPlates and set the old one to TidyPlatesPanel.lua.bak and then copy/paste the one you downloaded into that folder.

**Comment by korgen63** [comment]
Thank you so much, it'll finally be playable till a full update is done.

**Comment by Gaviin1242** [comment]
Appreciate the fix!  Even with that though, still getting the following error:


```
12x TidyPlatesHub/Templates.lua:761: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@TidyPlatesHub/Templates.lua"]:761: in function `CreateHubInterfacePanel'
[string "@TidyPlatesHub/Hub.lua"]:513: in main chunk

Locals:
objectName = "HubPanelSettingsTank"
panelTitle = "|cFF3782D1Tank Profile"
parentFrameName = "Tidy Plates"
panel = HubPanelSettingsTank_InterfaceOptionsPanel {
 BottomLeftCorner = Texture {
 }
 parent = "Tidy Plates"
 MainLabel = Frame {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 ScrollFrame = HubPanelSettingsTank_Scrollframe {
 }
 Warnings = Frame {
 }
 objectName = "HubPanelSettingsTank"
 WarningFrame = HubPanelSettingsTankWarningFrame {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
 Headings = <table> {
 }
 AlignmentColumn = HubPanelSettingsTank_AlignmentColumn {
 }
 ScrollFrameBorder = HubPanelSettingsTankScrollFrameBorder {
 }
 MainFrame = Frame {
 }
 TopEdge = Texture {
 }
 Center = Texture {
 }
 HeadingBookmarks = <table> {
 }
 name = "|cFF3782D1Tank Profile"
 BottomEdge = Texture {
 }
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
WarningFixButton = HubPanelSettingsTankWarningFixButton {
}
PasteThemeDataButton = HubPanelSettingsTankPasteThemeDataButton {
 tooltipText = "Loads settings from the stored template"
}
CopyThemeDataButton = HubPanelSettingsTankCopyThemeDataButton {
 tooltipText = "Set template using current settings"
}
ReloadThemeDataButton = HubPanelSettingsTankReloadThemeDataButton {
 tooltipText = "Resets the configuration to Default.  Holding down 'Shift' will also clear saved unit data, and restart your UI."
}
BookmarkButton = HubPanelSettingsTankBookmarkButton {
}
UnlinkButton = HubPanelSettingsTankUnlinkButton {
}
(*temporary) = nil
(*temporary) = HubPanelSettingsTank_InterfaceOptionsPanel {
 BottomLeftCorner = Texture {
 }
 parent = "Tidy Plates"
 MainLabel = Frame {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 ScrollFrame = HubPanelSettingsTank_Scrollframe {
 }
 Warnings = Frame {
 }
 objectName = "HubPanelSettingsTank"
 WarningFrame = HubPanelSettingsTankWarningFrame {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
 Headings = <table> {
 }
 AlignmentColumn = HubPanelSettingsTank_AlignmentColumn {
 }
 ScrollFrameBorder = HubPanelSettingsTankScrollFrameBorder {
 }
 MainFrame = Frame {
 }
 TopEdge = Texture {
 }
 Center = Texture {
 }
 HeadingBookmarks = <table> {
 }
 name = "|cFF3782D1Tank Profile"
 BottomEdge = Texture {
 }
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
PanelHelpers = <table> {
}
font = "Interface\Addons\TidyPlates\Media\DefaultFont.ttf"

```

**Comment by lzanita09** [comment]
Looks like the [deprecated](https://github.com/Gethe/wow-ui-source/blob/7b60bd43f05f53332184e7540bb958ecd6f48898/Interface/SharedXML/Settings/Blizzard_Deprecated.lua) `InterfaceOptions_AddCategory` function is finally removed, and it is causing problems here.

I'm not familiar with Lua or how the addon is written, but I was able to get it to "work" with a somewhat weird settings UI. I'm using mac os at the moment, so the directories might be different from windows, but the file names should be the same. You should be able to find these files within the addons folder of your retail wow folder.

#### Fix for the main setting
On `../TidyPlates/TidyPlatePanel.lua`, on line 14, change 
```
InterfaceOptions_AddCategory(TidyPlatesInterfacePanel);
``` 
to 
```lua
local category, layout = Settings.RegisterCanvasLayoutCategory(TidyPlatesInterfacePanel, "Tidy Plates")
Settings.RegisterAddOnCategory(category)
```

#### Fix for the profiles
This is where my knowledge for these things ends, I was not able to get all the profiles to show up as "subcategories". Nevertheless I was able to get them to work.

On `../TidyPlatesHub/Templates.lua`, on line 761, replace
```lua
InterfaceOptions_AddCategory(panel)
```
with
```lua
local category, layout = Settings.RegisterCanvasLayoutCategory(panel, panelTitle)
Settings.RegisterAddOnCategory(category)
```

After these two changes, `/reload ui` in the game and you should see the addon back to normal. Hopefully @ImogenBits is able to come back and fix this properly for us, the documentation linked above does have some extended explanation about how to build the settings with new APIs.

**Comment by httpsx** [comment]
I have created a PR that includes the complete restoration of the addon functionality, including the settings window
https://github.com/ImogenBits/tidyplates/pull/108

**Comment by ImogenBits** [comment]
I'm working on a fix. The codebase for this addon was written over a decade ago by someone else and is pretty convoluted, so it's hard and might take some time. I'll try to get it into a somewhat working state asap and then release that update, and then might try to actually get things fixed and up to date properly.

**Comment by ImogenBits** [comment]
Pushed a release that fixes the immediate bugs and makes it work as it did before 11.0.
