### ISSUE TITLE
Lua failure

### ISSUE THREAD

**Issue by Adorizoe** [ImogenBits/tidyplates#109]
-------------------------------
Message: Interface/AddOns/TidyPlates/TidyPlatesUtility.lua:697: attempt to call method 'SetColorRGB' (a nil value)
Time: Sun Aug  4 10:30:36 2024
Count: 1
Stack: Interface/AddOns/TidyPlates/TidyPlatesUtility.lua:697: attempt to call method 'SetColorRGB' (a nil value)
[string "=[C]"]: in function `SetColorRGB'
[string "@Interface/AddOns/TidyPlates/TidyPlatesUtility.lua"]:697: in function <Interface/AddOns/TidyPlates/TidyPlatesUtility.lua:692>
[string "@Interface/AddOns/TidyPlates/TidyPlatesUtility.lua"]:714: in function <Interface/AddOns/TidyPlates/TidyPlatesUtility.lua:714>

Locals: 
-------------------------------
failure massage above
showing when try to change Threat Colors at any profile

![20240804-10 4003_](https://github.com/user-attachments/assets/76623abe-782f-4130-b669-9b82806802a6)

**Comment by ImogenBits** [comment]
fixed in new release
