### ISSUE TITLE
Default Blizzard nameplate showing briefly under Tidyplates nameplate, especially on warrior

### ISSUE THREAD

**Issue by scorpgul** [ImogenBits/tidyplates#11]
This is an issue that was fixed a week ago by the author but now with the newest update 6.20.0, it is introduced again. You can notice it clearly when charging/leaping to a mob on a warrior. The Blizzard nameplate will appear then quickly disappear underneath the Tidyplates nameplate.

**Comment by ImogenBits** [comment]
I can't reproduce this currently. Can you describe the actions you're taking when this happens in more detail?

**Comment by zofia1347** [comment]
I think I'm getting the same issue as well. It happens pretty much every time I'm using a 2P mount. When a player hops on, that brief time they are in the air it causes the Blizzard nameplate to appear then disappear once they settle on. Not sure if it helps but much hopefully it does!
![image](https://user-images.githubusercontent.com/73046345/97113432-8912eb00-16a7-11eb-8a18-374f1d70b83c.png)

**Comment by ImogenBits** [comment]
Yeah that helped a lot! Made a fix, not sure if this breaks something else though. If it doesn't it'll be in the next patch.
