### ISSUE TITLE
TWW Beta LUA Errors

### ISSUE THREAD

**Issue by MatteoLombardi** [ImogenBits/tidyplates#110]
Hey, tried installing the 11.0 fix for retail on the beta server, but the bars disappear like they did when prepatch dropped, might need a look at it to be ready in advance for expac drop!

**Comment by httpsx** [comment]
Hi, I created pull request [#111](https://github.com/ImogenBits/tidyplates/pull/111) which fixes the errors in 11.0.2. 
You can use my branch if you want to use it now on the beta server: https://github.com/httpsx/tidyplates/tree/TWW_Beta_11.0.2

**Comment by ImogenBits** [comment]
fixed in new release
