### ISSUE TITLE
New error with TWW 11.0.2

### ISSUE THREAD

**Issue by Gaviin1242** [ImogenBits/tidyplates#112]
Not sure why Bliz feels the need to change API stuff between minor patches, but here we are.

28x TidyPlatesWidgets/TankTrack.lua:77: attempt to call global 'UnitBuff' (a nil value)
[string "@TidyPlatesWidgets/TankTrack.lua"]:77: in function <TidyPlatesWidgets/TankTrack.lua:62>
[string "@TidyPlatesWidgets/TankTrack.lua"]:151: in function <TidyPlatesWidgets/TankTrack.lua:141>

Locals:
spellID = nil
name = nil
_ = nil
playerTankAura = false
specializationIndex = 1
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "attempt to call global 'UnitBuff' (a nil value)"
playerTankRole = false
TankAuras = <table> {
 5487 = true
 115069 = true
 25780 = true
 48263 = true
}

**Comment by FuriousProgrammer** [comment]
This is actually a fairly old deprecation that just got removed this patch!
https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes#Deprecated_API

**Comment by httpsx** [comment]
Hi, I created pull request https://github.com/ImogenBits/tidyplates/pull/111 which fixes the errors in 11.0.2.
You can use my branch if you want to use it now: https://github.com/httpsx/tidyplates/tree/TWW_Beta_11.0.2

**Comment by Gaviin1242** [comment]
Thanks, guys, that did it!

**Comment by memo0704** [comment]
> Hi, I created pull request #111 which fixes the errors in 11.0.2. You can use my branch if you want to use it now: https://github.com/httpsx/tidyplates/tree/TWW_Beta_11.0.2

My friend how can i implement your fix? I'm kind of new at addons

**Comment by bull88-freddy** [comment]
here u can download this 

[https://github.com/user-attachments/files/16610653/TidyPlates.zip]

**Comment by korgen63** [comment]
I installed last update from Curseforge app but it still don't work.
![WoWScrnShot_081424_120223](https://github.com/user-attachments/assets/bbfb92f8-20ab-409a-b4b4-7c8b30715b42)

**Comment by bull88-freddy** [comment]
> here u can download this
> 
> [https://github.com/user-attachments/files/16610653/TidyPlates.zip](url)

**Comment by korgen63** [comment]
Your link doesn't work (No results matched your search)

**Comment by bull88-freddy** [comment]
> here u can download this
> 
> [https://www.file-upload.net/download-15373064/TidyPlates.zip.html](url)

now ^^

**Comment by bull88-freddy** [comment]
[TidyPlates.zip](https://github.com/user-attachments/files/16611835/TidyPlates.zip)

**Comment by korgen63** [comment]
Thank you, it works now ^^

**Comment by UserNoneed** [comment]
hi,

With the link above it works again. 
On the other hand, I no longer have the remaining timers displayed on the spells. 
Thanks

**Comment by Healerusethis** [comment]
Hi, i used your link. But still doen't work for me. 
![Capture d’écran 2024-08-15 032037](https://github.com/user-attachments/assets/c0436cfa-7b59-44a0-b828-51e3a69a818e)

**Comment by bull88-freddy** [comment]
u must copy all files

**Comment by ImogenBits** [comment]
fixed in new release
