### ISSUE TITLE
thewarwithin 11.0.2 error

### ISSUE THREAD

**Issue by ghnicole** [ImogenBits/tidyplates#114]
### tidy plates are my favorite Unit Frames plugin, please help to fix them

Message: ...rface/AddOns/TidyPlatesHub/functions/ColorThreat.lua:370 attempt to index field 'Color' (a nil value)
Time: Tue Aug 20 14:22:35 2024
Count: 10000 - **Infinite increase**
Stack: ...rface/AddOns/TidyPlatesHub/functions/ColorThreat.lua:370: attempt to index field 'Color' (a nil value)
[string " @Interface/AddOns/TidyPlatesHub/functions/ColorThreat.lua:370: in function 'func'
[string " @Interface/AddOns/TidyPlatesHub/functions/ColorThreat.lua:534: in function 'SetNameColor'
[string " @Interface/AddOns/TidyPlates/TidyPlatesCore.lua"]:728: in function <Interface/AddOns/TidyPlates/TidyPlatesCore.lua:717>
[string " @Interface/AddOns/TidyPlates/TidyPlatesCore.lua"]:791: in function <Interface/AddOns/TidyPlates/TidyPlatesCore.lua:772>
[string " @Interface/AddOns/TidyPlates/TidyPlatesCore.lua"]:137: in function <Interface/AddOns/TidyPlates/TidyPlatesCore.lua:293>
......

**Comment by ImogenBits** [comment]
thanks for the report, it's fixed in the new release.
