### ISSUE TITLE
Shadowlands Special Health Bars

### ISSUE THREAD

**Issue by Draenik** [ImogenBits/tidyplates#14]
Tidy Plates breaks some of the "special" health bars displayed in some Shadowlands content.

For the quest "The Work of One's Hands" (Bastion introductory quest), you have to control the "heat" of a forge.  This is controlled by an NPC with the name "Hold the heat steady" (actual NPC, health bar, can be focused using mouseover focus macro but not targeted).  There are no buffs or debuffs on this NPC, nor does the HP ever change from full, however with Tidy Plates disabled, you can see a "middle" point where you have to keep the heat of the furnace at, and a sliding indicator bar showing how hot the forge is.

![Heat - Tidy Plates disabled](https://user-images.githubusercontent.com/66196568/97122157-b75ffb80-1777-11eb-8c36-74e57e50347b.png)

![Heat - Tidy Plates enabled](https://user-images.githubusercontent.com/66196568/97122159-b929bf00-1777-11eb-987c-80144e30208c.png)

**Comment by ImogenBits** [comment]
Thanks for the report! I'll try to fix it, but I don't think I'll prioritise it until SL hits live servers (or is about to), so if you're using it on the beta you probably want to turn it off for those quests.

**Comment by Draenik** [comment]
Hey, not nagging I promise.  Just wondering if this will likely be fixed prior to tomorrow, or if we'll have to disable the addon for this quest.

I did try to add this NPC name to the filter, however that just makes it not display at all, and not just not skin this nameplate.  Perhaps a similar blacklist of nameplates to not skin (and not disable either).

**Comment by ImogenBits** [comment]
Haha don't worry! Here's my plan: I have a fix in mind that I think should work, but I haven't been able to test it. On release night I will level until then and see if it does, if it does I will push the fix to be released.
If you want to try it yourself on release night you can download the version on [this branch ](https://github.com/ImogenBits/tidyplates/tree/smallFixes) tomorrow (haven't yet pushed everything, will in a few hours).

**Comment by Draenik** [comment]
Hah no worries, again wasn't a nag, you're doing a great job  :).  I'll wait for the official release, happy leveling!

**Comment by ImogenBits** [comment]
Fix I found is working and pushed into the main branch. Released a new version with it and some other minor bugfixes, but no new features. Should be up on Curseforge in a few minutes.

Happy leveling everone!
