### ISSUE TITLE
Wow turns down Tidy plates nameplates

### ISSUE THREAD

**Issue by Springsou** [ImogenBits/tidyplates#26]
Hi! Faced a problem and have no idea how to fix it as it never happened before the SL is out. Wow for some reason turns down tidy plates nameplates and I have to press standatd key V to make them appear again, but in a couple of minutes nameplates dissapear again and I have to press V again. Once I turn off TP and use standatd Blizzard bars everything is good and they don't dissapear. I heard that Blizzard changed something in nameplates lua code so maybe that's a problem.

**Comment by ImogenBits** [comment]
Is this still an issue? If so, I'll need more info to be able to fix it. [This wiki page](https://github.com/ImogenBits/tidyplates/wiki/Bug-Reports) describes in more detail what I mean.
