### ISSUE TITLE
Remove level bar area

### ISSUE THREAD

**Issue by chernov-iv** [ImogenBits/tidyplates#27]
Hi guys,

Thanks for the great addon. Is there a way to remove target level bar area?
![image](https://user-images.githubusercontent.com/6865878/101051609-5ef9f600-358e-11eb-8ac8-d68a88e9fa2e.png)

I tried here but it does not seem to do anything:
![image](https://user-images.githubusercontent.com/6865878/101051692-733df300-358e-11eb-80d8-36542bf6c47b.png)

Appreciate your help.

**Comment by ImogenBits** [comment]
This does not look like you are using TidyPlates. Maybe you're using ThreatPlates? That used to be a theme for this addon but now is a totally separate addon.
