### ISSUE TITLE
Friendly bars not working in dungeon

### ISSUE THREAD

**Issue by NeonShard** [ImogenBits/tidyplates#28]
I started healing recently, so I first started using friendly bars. Enemy bars were and are wunning just fine, but when I opened friendly nameplates problems appeared. Did not made muc htesting, but at first sight, in open world everything is okay. When I joined dungeon, friendly bars started showing color by enemy class, altrough it was set to show color by HP (and it showed in open world). To add on it, bars sometimes randomly swapped between players, showing wrong health amount as well as randomly swapping names - teammates had name of each other, as well as class. I've noticed then new version is out, so I updated it. Now . when I join instance, friendly nameplates don't show at all. They do push stacking nameplates away, but are not visible by any means. Enemy plates working still fine. If it is just mine problem, please give me suggestion how to fix this.

**Comment by FlauFlauw** [comment]
Hey, same problem here.

**Comment by Cutiepaw** [comment]
Hi! Same here.

**Comment by ignaciobfp** [comment]
Same problem here aswell. In case it can clarify, I made some screenshots.

Outside dungeon:
![Wow_2020-12-15_16-50-11](https://user-images.githubusercontent.com/11695164/102259416-5f3fad00-3f0f-11eb-9c50-e76f2a2558c4.jpg)

Inside dungeon:
![Wow_2020-12-15_16-44-23](https://user-images.githubusercontent.com/11695164/102259448-6961ab80-3f0f-11eb-99cf-7055eac6cab5.jpg)

May be related to other issues. However in my case they do not disapear after some time nor overlay the stock ones.

**Comment by NeonShard** [comment]
Recently I found out that Blizzard disabled custom friendly bars in instances (more than year ago). You have bars changed to Blizzard default automatically in instance as it should be. As I got bars invisible in instance, It may be caused by bad coding of addon, not showing itself, while denying default Blizzard bar to show. Yesterday I tried Threat Plates as alternative. It works good and have aldo option of small tweaking of Blizzard default bars. It will have to suffice for now, but I would like to get Tidy Plates visual back, other nameplate addons looks just gross for me.

**Comment by ignaciobfp** [comment]
Oh, I see, thank you very much for the information... I just returned playing and only used this addon for nameplates, so I did not notice the behaviour, I apologize!

**Comment by ImogenBits** [comment]
sorry it took this long, but is the issue just that TidyPlates bars don't work in dungeons/raids? If so, then I can indeed confirm that this is a decisison blizzard made and there is nothing we can do to get around it. If the problem is different, then I'll need a more detailed description.
