### ISSUE TITLE
PVP: health difference from plates to actual HP

### ISSUE THREAD

**Issue by RiskfreeDraenor** [ImogenBits/tidyplates#30]
So i been noticing this in arena, 2v2 and 3v3, sometimes in bg as well, On tidyplates i see the enemy half hp or whatever, but when i go click on him, on my target frame he is actually full hp. 
So the health shown by tidyplates its either delayed or displaying wrong? not too sure. 
but had this happen a LOT of times in the past few days of arena push, kinda annoying.

**Comment by RiskfreeDraenor** [comment]
https://i.imgur.com/Ozts4Pj.jpg  example here

**Comment by RiskfreeDraenor** [comment]
Still happening even removing every other addon, and being on a different computer. /shrug

**Comment by djschalk** [comment]
This is also happening to me. Can post screen shots.

**Comment by LiamCoyle** [comment]
happened to me in BG

**Comment by hoboedd** [comment]
Hey, I just wanted to let you know this was a common occurrence all throughout BFA for me. It's related to absorbs, that's about as much as I can tell.

**Comment by ImogenBits** [comment]
should be fixed with the next update
