### ISSUE TITLE
Combo Point-like circles appear and disappear

### ISSUE THREAD

**Issue by SheriffV2** [ImogenBits/tidyplates#32]
Occassionally circles of different colors will appear and throttle above a plate then disappear.. don't know what's causing it. Turning combo points off doesn't seem to affect it.

**Comment by ImogenBits** [comment]
Sorry it took so long.
I'm not quite sure what exactly you are talking about. Can you give me a more detailed description of what you are doing when this happens? Eg your class/spec, your settings, what you do, what exactly it looks like (ideally with a screencap), etc

**Comment by DosParkers** [comment]
This is what it looks like. Prot Warrior. Never seen the dots before today.
![dots](https://user-images.githubusercontent.com/6854292/109408909-01daca00-795c-11eb-926e-0442c11ad8a7.png)

**Comment by ImogenBits** [comment]
ah ok, I think I got the fix now
does turning off the combo point option in Tidyplates fix it for you at the moment?

**Comment by DosParkers** [comment]
I turned off the combo point option and reloaded ui and it fixed it.
