### ISSUE TITLE
BigDebuffs & Tidyplates conflict

### ISSUE THREAD

**Issue by bzanelato** [ImogenBits/tidyplates#35]
Hi,
BigDebuffs is supposed to show on nameplates but it's not working when tidyplates is active. Any way to make them work together ?

**Comment by BTC1M** [comment]
It's not working for me neither (when tidy plates is active).
I'm looking to have a better display of ennemy debuffs above the nameplates but i can't find a solution for now. I need the debuffs icons size to be bigger for CC debuffs.

**Comment by jsmenzies** [comment]
Hey,

I believe this is an issue with BigDebuffs. If you look at this BD PR (https://github.com/jordonwow/bigdebuffs/issues/103) you can see the OP added the ability to get the ThreatPlates anchor and so now they are compatible.

I think BD needs to do the same thing for TidyPlates but unfortunately I raised an issue and it hasn't been addressed yet (https://github.com/jordonwow/bigdebuffs/issues/186)

I don't know LUA and im unsure how one addon can "get" the anchor from another but if the maintainer or TP knows how this can be done it would be great if they could add open PR to BD.

Cheers

**Comment by ImogenBits** [comment]
This is an issue with BigDebuff. The way they integrate their buffs into the nameplates only works with specific other addons. I've submitted a request for them to add TidyPlates support, but can't really do more than that.
