### ISSUE TITLE
Skull icon(level) randomly appear

### ISSUE THREAD

**Issue by nakinacho** [ImogenBits/tidyplates#38]
Hello,

the skull icon(level) appears and disappears randomly on the boss's health bar in the raid castle of nathria.

I've unchecked the level indicator but it still there.
![image_2021-01-07_18-09-30](https://user-images.githubusercontent.com/77095346/103920264-bce3a580-5119-11eb-8aff-b392ce45e21b.png)

**Comment by ImogenBits** [comment]
fixed with next update
