### ISSUE TITLE
c_questlog issues

### ISSUE THREAD

**Issue by Inhumed** [ImogenBits/tidyplates#4]
Below is the message I got when doing some quests in Zuldazar as a alt I'm leveling up.

Message: Usage: local info = C_QuestLog.GetInfo(questLogIndex)
Time: Sun Oct 18 02:42:33 2020
Count: 9
Stack: Usage: local info = C_QuestLog.GetInfo(questLogIndex)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:289: in function `AddQuestCacheEntry'
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:302: in function `UpdateQuestCacheEntry'
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:358: in function `?'
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua"]:36: in function <...ns\TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua:30>

Locals:

**Comment by ImogenBits** [comment]
This actually isn't an issue with this addon. The addon you're looking for is called Thread Plates. It seems that Thread Plates used to be an extension for Tidy Plates, but that is no longer the case.
[Here's](https://www.curseforge.com/wow/addons/tidy-plates-threat-plates) the Curseforge page of Threat Plates, their Github is also linked there.
