### ISSUE TITLE
neutral enemy health bar

### ISSUE THREAD

**Issue by alsuperhero1** [ImogenBits/tidyplates#45]
I'm trying to hide neutral enemy heath bars but when I engage them in combat there still hidden, is this a bug or not a feature yet or is there another way to do it that I missed?

**Comment by ImogenBits** [comment]
assuming you mean the "Force Headline on Neutral Units" option with hiding them, that wasn't a feature yet, but I quickly added it. With the next update you can have it show a nameplate while in combat and a headline out of combat.

If you actually meant something else, please describe your issue in more detail so I can fix the actual issue.

**Comment by alsuperhero1** [comment]
No that's what I meant thanks for adding it :)
