### ISSUE TITLE
Continuous "false" in chat window

### ISSUE THREAD

**Issue by Glaszstaff** [ImogenBits/tidyplates#46]
Just updated Tidy Plates with the recent 6.20.3 update and I am getting a constant "false" text output in my chat box over and over again. The UI works fine but I can't get the messages to stop rolling in by other than disabling the entire addon. 

I have tried reinstalling and completely deleting the folder and fresh installing the addon to no different result.

If I am missing something please feel free to point it out. I'd really hate to move to something like ElvUi after so many years with my current interface setup.

**Comment by ImogenBits** [comment]
ah fuck, I left a debug thing in the code, sorry!
I made a new release that fixes this, should be up on CurseForge in a few minutes

**Comment by Glaszstaff** [comment]
Sweet, It worked! You're the best. Sorry to hear about your busy schedule. Keep up the good work. I appreciate everything you are doing by keeping the addon alive!
