### ISSUE TITLE
Lua error in M+ since version 6.20.3

### ISSUE THREAD

**Issue by srobins6** [ImogenBits/tidyplates#48]
Upon starting M+, getting this Lua error:

Message: Interface\AddOns\TidyPlates\TidyPlatesUtility.lua:213: attempt to index local 'progText' (a nil value)
Time: Tue Mar  2 14:34:50 2021
Count: 750
Stack: Interface\AddOns\TidyPlates\TidyPlatesUtility.lua:213: attempt to index local 'progText' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\TidyPlates\TidyPlatesUtility.lua"]:213: in function <Interface\AddOns\TidyPlates\TidyPlatesUtility.lua:189>
[string "@Interface\AddOns\TidyPlatesHub\functions\Text.lua"]:435: in function <Interface\AddOns\TidyPlatesHub\functions\Text.lua:431>
[string "@Interface\AddOns\TidyPlatesHub\functions\Text.lua"]:461: in function <Interface\AddOns\TidyPlatesHub\functions\Text.lua:454>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:787: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:774>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:317: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:293>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:422: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:412>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:142: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:121>

Locals: 

Appears to be an issue with the % for M+, since that functionality isn't working while this error is going on. If I revert to 6.20.2, it works, but upgrading to 6.20.4 does not fix it.

**Comment by ImogenBits** [comment]
this is a bug with the quest text display option for the headline text. Should be fixed with the next release, but in the meantime you should be able to stop it by switching to another text display or turning off the headline display in keys.
