### ISSUE TITLE
Undetermined dots under frames

### ISSUE THREAD

**Issue by FrenzySmile** [ImogenBits/tidyplates#49]
Hello!
Undetermined dots began to appear above the frames of hostile characters.
Please help!
![TidyPlates bug](https://user-images.githubusercontent.com/80243324/110285835-0c592b80-800e-11eb-82d2-981b2f275136.jpg)
My addons used with Tidyplates:
1) NameplateCooldowns
2) OmniCC
3) OmniBar
4) BigDebuffs
5) BattleGroundEnemies
6) Weak auras

Best regards

**Comment by Caraman24** [comment]
disable tug o threat indicator

**Comment by ImogenBits** [comment]
Duplicate of #32
