### ISSUE TITLE
Healthbar not updating

### ISSUE THREAD

**Issue by djschalk** [ImogenBits/tidyplates#51]
Often times the nameplate will show an npc or enemy player at low hp when in reality they are full hp. Please fix this, it makes tidy plates unusable but every other nameplate addon sucks in comparison to tidy plates. I don't want to switch :(

**Comment by Trigstyle1** [comment]
The creator sucks I don't think he knows how to fix it he released a new update and it's still broken lmao look into Threat Plates it's pretty solid you can look around for different presets to import if you don't want to customize it yourself.

**Comment by MiniFredx** [comment]
To add more detail, say a mage uses his 3 shields with his legendary and gets a huge bubble. The bubble expires but his hp is still at full. His tidyplate health bar will show him at 3/4 health and not fix unless I turn off all nameplates and turn them back on with ctrl+v.

**Comment by ImogenBits** [comment]
should be fixed with the next update
