### ISSUE TITLE
Changing font color for cast bar in .lua?

### ISSUE THREAD

**Issue by subzero364** [ImogenBits/tidyplates#53]
Hi,

First of all thank you very much for the effort put into this addon. My favourite plates by far.

Where in the .lua (and in which one) can I change the font color for the spell name that appears on the cast bar? I have been able to edit basically every other color/feature through the .lua except this, which I can't seem to find anywhere. For reference I am using the Neon theme.

Thanks!

**Comment by ImogenBits** [comment]
you can go to line 218 in TidyPlates/TidyPlatesCore.lua and add `visual.spelltext:SetTextColor(r, g, b, a)` in the next line. So your code will then look like
`		-- Cast Bar Frame - Highest Frame
		visual.castborder = castbar:CreateTexture(nil, "ARTWORK")
		visual.castnostop = castbar:CreateTexture(nil, "ARTWORK")
		visual.spellicon = castbar:CreateTexture(nil, "OVERLAY")
		visual.spelltext = castbar:CreateFontString(nil, "OVERLAY")
        visual.spelltext:SetTextColor(1, 0, 0)
		-- Set Base Properties
		visual.raidicon:SetTexture("Interface\\TargetingFrame\\UI-RaidTargetingIcons")
		visual.highlight:SetAllPoints(visual.healthborder)
		visual.highlight:SetBlendMode("ADD")`
