### ISSUE TITLE
Nameplates not showing or acting strange, generating hundreds of errors per minute for each affected target

### ISSUE THREAD

**Issue by blackmamba96** [ImogenBits/tidyplates#54]
Hi there!

I've been using TidyPlates since forever ago and never had this issue before. In fact, it only happens to my new orc shaman that I boosted yesterday. Approaching enemies that are engaged in combat by someone else either makes the colour of the nameplate white-ish or it does not appear at all. This begins to stack errors really quickly (about 1000 errors per minute if it is only a single enemy in this state within vision, but usually there is way more of those like in Maldraxxus where different armies fight each other). I have 4 other characters that visit the same zones, fight the same enemies but never experience this issue. 
And yes, while in the open world that is a bit irrelevant, after visiting a dungeon, the issue still sometimes appears, making it extremely difficult to track targets or know what I am targetting without double-checking every time and also perform decently. While my shaman is still in the levelling stage, I don't want to be useless when it is doing mythic plus in a week or so.

![image](https://user-images.githubusercontent.com/15032548/113168163-1527d080-924d-11eb-813f-110d75bd62bf.png)
^ errors stacking up

![image](https://user-images.githubusercontent.com/15032548/113168753-9e3f0780-924d-11eb-91ff-0050c489d4f2.png)
^ example of enemies engaged by another player showing no nameplates and generating errors each

![image](https://user-images.githubusercontent.com/15032548/113168908-c4fd3e00-924d-11eb-8b7f-21b88ffd28b7.png)
^ same as the one above but engaged by me and still not showing nameplates and generating errors

![image](https://user-images.githubusercontent.com/15032548/113169267-1c031300-924e-11eb-89ce-316d93d8c18c.png)
^ how it is on my other characters and how it's supposed to be

![image](https://user-images.githubusercontent.com/15032548/113169600-6edcca80-924e-11eb-83ca-73c9954d6c23.png)
^ how it appears half the time on my shaman and causing endless errors

Here's the error that I am getting repeatedly (this is what generated over a 5-10 min period of just watching an enemy get attacked by the guards Maldraxxus):

```
11790x TidyPlatesHub\functions\Text.lua:156: attempt to concatenate global 'unitid' (a nil value)
[string "@TidyPlatesHub\functions\Text.lua"]:156: in function <TidyPlatesHub\functions\Text.lua:154>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@TidyPlates\TidyPlatesCore.lua"]:787: in function <TidyPlates\TidyPlatesCore.lua:774>
[string "@TidyPlates\TidyPlatesCore.lua"]:317: in function <TidyPlates\TidyPlatesCore.lua:293>
[string "@TidyPlates\TidyPlatesCore.lua"]:422: in function <TidyPlates\TidyPlatesCore.lua:412>
[string "@TidyPlates\TidyPlatesCore.lua"]:142: in function <TidyPlates\TidyPlatesCore.lua:121>

Locals:
unit = <table> {
 guid = "Creature-0-4237-2222-944-161399-0000648E56"
 isMouseover = false
 class = ""
 rawName = "Fleshsewn Brawler"
 threatSituation = "LOW"
 red = 0.999998
 levelcolorRed = 1
 unitid = "nameplate1"
 isMini = true
 pvpname = "Fleshsewn Brawler"
 levelcolorBlue = 0
 isBoss = false
 isFocus = false
 healthmax = 2697
 isTarget = false
 levelcolorGreen = 0.820000
 isInCombat = true
 absorbmax = 0
 isTapped = false
 absorb = 0
 blue = 0
 style = "Default"
 isMarked = false
 level = 50
 type = "NPC"
 isCasting = false
 reaction = "NEUTRAL"
 green = 0.999998
 health = 1888
 threatValue = 0
 isDangerous = false
 name = "Fleshsewn Brawler"
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "target"
(*temporary) = "attempt to concatenate global 'unitid' (a nil value)"
```

**Comment by bismarck2186** [comment]
i have the same issue I tried to turn all addons off but no positv effects. Another thing i recognized is that the targeted enemy is not that in the error message for example: Necromantic Scourer becomes Stalwart Death Element; or i attacked Keensnout Gromit and the Error says it has 1.2 million health and is a elite enemy called Hargitas

**Comment by ImogenBits** [comment]
should be fixed in the next release
