### ISSUE TITLE
Personal Resource Display - Health part missing with Addon enabled.

### ISSUE THREAD

**Issue by AyAyRon20** [ImogenBits/tidyplates#6]
When I have Tidy plates enabled, the health section of the Personal Resource Display is missing.
When I /reload, it appears for one fight, once it fades for non combat and comes back when in combat, the health section is missing. 
Disabling the addon fixes the issue
No bugs are reported in the bug sack for this 
![image](https://user-images.githubusercontent.com/73082765/96387464-a2202580-11e9-11eb-89c9-222036034de3.png)

**Comment by ImogenBits** [comment]
Duplicate of #1
