### ISSUE TITLE
TidyPlatesCore.lua:973: Attempt to access forbidden object from code tainted by an AddOn

### ISSUE THREAD

**Issue by RavenDT** [ImogenBits/tidyplates#63]
Running Tidy Plates 6.20.10, the following occurs when trying to enable all nameplates (not just enemies), inside of a raid instance.

```
Message: Interface\AddOns\TidyPlates\TidyPlatesCore.lua:973: Attempt to access forbidden object from code tainted by an AddOn
Time: Thu Sep  9 21:42:19 2021
Count: 1
Stack: Interface\AddOns\TidyPlates\TidyPlatesCore.lua:973: Attempt to access forbidden object from code tainted by an AddOn

Locals: 
```

I know a while back they made it where you can't alter friendly player nameplates in Mythic Dungeons and Raids, but never used to get this error until just tonight.

**Comment by kuya1284** [comment]
I get this error as well, but so far only in Draenor. I haven't come across this error yet in Azeroth, Kalimdor, and Pandaria. I haven't tested other zones yet.

**Comment by ImogenBits** [comment]
fyi, i don't have an active wow subscription right now so I'm not really able to fix bugs at the moment.
I'll take a look at it once I get back but in the meantime I think the best option is to use a different addon if the error is too problematic. sorry about any annoyance that's caused.

**Comment by kuya1284** [comment]
> fyi, i don't have an active wow subscription right now so I'm not really able to fix bugs at the moment. I'll take a look at it once I get back but in the meantime I think the best option is to use a different addon if the error is too problematic. sorry about any annoyance that's caused.

No worries. Thank you for the heads up. All the effort you put in has been greatly appreciated. No need to apologize, especially since you were working on this on your own personal time. I develop web apps, so I totally get it. Take care and thanks again for everything.

**Comment by ImogenBits** [comment]
should be fixed in this release
