### ISSUE TITLE
Overlap with BigDebuffs

### ISSUE THREAD

**Issue by Alsheee** [ImogenBits/tidyplates#74]
Hi, I am attempting to use BlizzardPlates with BigDebuffs, however noticed that BigDebuffs gets layered under BlizzardPlates' level display. 
Anyone know if its possible to either remove the end part of the blizzard plate or allow BigDebuffs to be layered in front?
![image](https://user-images.githubusercontent.com/115969507/196094616-411e11c2-2e3f-4832-bc14-e03caedec954.png)
![image](https://user-images.githubusercontent.com/115969507/196094734-71c1303e-0d34-4778-95f4-eb38f8ee778c.png)

**Comment by Spkilla** [comment]
just set the x axis of the debuff to 20 or whatever number so it doesnt cover
![WoWScrnShot_102622_171157](https://user-images.githubusercontent.com/38851009/198139140-d4c2708b-3607-4dd8-b8e3-8aa71ea7578f.jpg)
