### ISSUE TITLE
Does not work with Dragonflight prepatch. Prevents keys from being pressed

### ISSUE THREAD

**Issue by scorpgul** [ImogenBits/tidyplates#75]
Now that Dragonflight prepatch is out, Tidyplates has stopped working completely and even prevent buttons from being pressed. Please update this great addon.

thanks

**Comment by httpsx** [comment]
Hello, you can use my fix for dragonflight 10.0
https://github.com/httpsx/tidyplates

**Comment by ImogenBits** [comment]
merged into this repo, should be available on curseforge within a few minutes
