### ISSUE TITLE
Will there be an update of the standard themes, hub, etc?

### ISSUE THREAD

**Issue by StanoRiga** [ImogenBits/tidyplates#77]
The core addon was updated recently.
My question is if the addon which were formerly distributed with the core addon also be updated.

The addons in question:

1. Tidy Plates Hub
2. Tidy Plates Widgets
3. Tidy Plates: Graphite
4. Tidy Plates: Grey Theme
5. Tidy Plates: Neon Theme
6. Tidy Plates: Quatre Theme

Thank you

**Comment by ImogenBits** [comment]
forgot to update their version numbers too, thanks for reminding me, threy're updated now
