### ISSUE TITLE
TidyPlates not working

### ISSUE THREAD

**Issue by Vortilion** [ImogenBits/tidyplates#78]
Installed the addon via curse-client, checked if its enabled (it is, alongside all its parts). Still its not showing up. Also I can't open the menu via /tidyplates. If I try it won't let me send the command (enter does nothing, /tidyplates stays in the chatbar).

**Comment by ffejwolf** [comment]
I have a similar set of issues.  Tidyplates loads but I can't save my settings, and typing /hub or /tidyplates doesn't come up with an error but it does nothing in the chat window.

**Comment by cars11** [comment]
same. doesn't work at all. i can't even press enter when i type /tidyplates

**Comment by ImogenBits** [comment]
should be fixed now
