### ISSUE TITLE
Latest version issue with Blizzard personal resource display

### ISSUE THREAD

**Issue by xxroots** [ImogenBits/tidyplates#8]
Like the tittle says, i use the game personal resource display under my character and as soon as i get out of combat the health bar and buffs above it disspear, im only left with the mana/energy bad showing when entering combar again. If i reload the ui it gets fixed but bugs again as soon as i get out of combat. Thanks. 

release_6.19.6

**Comment by ImogenBits** [comment]
Duplicate of #1
